#!/bin/bash

rRw=$1
prog=$2


if [ $rRw == '-r' ]
then
  repo="https://github.com/ThyCowLord/"+$prog
  git clone $repo
fi
if [ $rRw == '-w' ]
then
  availprogs=("matrix", "roulette", "willow", "pine")
  if [ $prog in $availableprogs ]
  then
    repo="https://raw.githubusercontent.com/ThyCowLord/ThyCowLord.github.io/master/code/"$prog
    wget $repo
  fi
fi
